export default {
  netflix: "Netflix",
  youtube: "YouTube",
  spotify: "Spotify",
  "uber-backend": "Uber",
  "payment-system": "Payment System",
  "chat-system": "Chat System",
  "news-feed": "News Feed",
  "notification-system": "Notification System",
  "google-drive": "Google Drive",
  "url-shortener": "URL Shortener",
  pastebin: "Pastebin",
  "rate-limiter": "Rate Limiter",
  "ticket-booking": "Ticket Booking",
  "unique-id-generator": "Unique ID Generator",
  "recommendation-system": "Recommendation System",
  "google-file-system": "Google File System (GFS)",
  "salesforce-architecture": "Salesforce Architecture",
  "google-ads-auction": "Google Ads Auction"
}
