export default {
  "api-design-rest-graphql-grpc": "API Design: REST vs GraphQL vs gRPC",
  "api-gateway-pattern": "API Gateway Pattern",
  "audio-streaming-spotify": "Audio Streaming (Spotify)",
  "caching-strategies": "Caching Strategies",
  "cdn-edge-computing-media": "CDN & Edge Computing for Media",
  "circuit-breaker-pattern": "Circuit Breaker Pattern",
  "cms-design": "CMS Design",
  "collaborative-editing-google-docs": "Collaborative Editing (Google Docs)",
  "cqrs-pattern": "CQRS Pattern",
  "database-replication": "Database Replication",
  "database-indexing-deep-dive": "Database Indexing Deep Dive",
  "database-sharding": "Database Sharding",
  "design-typeahead-search": "Design Typeahead Search",
  "distributed-tracing": "Distributed Tracing",
  "event-driven-architecture": "Event-Driven Architecture",
  "flash-sales": "Flash Sales",
  "high-concurrency-api": "High Concurrency API",
  "kubernetes-basics": "Kubernetes Basics",
  "live-streaming-twitch": "Live Streaming (Twitch)",
  "load-balancing-strategies": "Load Balancing Strategies",
  "message-queues-kafka-rabbitmq": "Message Queues: Kafka vs RabbitMQ",
  "monolith-to-microservices": "Monolith to Microservices",
  "observability-monitoring": "Observability & Monitoring",
  "online-gaming-backend": "Online Gaming Backend",
  "pdf-converter": "PDF Converter",
  "rate-limiting": "Rate Limiting",
  "saga-pattern": "Saga Pattern",
  "search-engine-architecture": "Search Engine Architecture",
  "service-discovery": "Service Discovery",
  "social-media-feed": "Social Media Feed",
  "ticket-booking-system": "Ticket Booking System",
  "video-conferencing": "Video Conferencing",
  "video-streaming-platform": "Video Streaming Platform",
  "websocket-architecture": "WebSocket Architecture"
}
