export default {
  index: "Overview",
  "what-is-an-agent": "🟢 What is an AI Agent?",
  "llm-fundamentals-for-agents": "🟢 LLM Fundamentals for Agent Builders",
  "react-pattern": "🟢 ReAct Pattern",
  "tool-use-function-calling": "🟢 Tool Use & Function Calling",
  "prompt-engineering-for-agents": "🟡 Prompt Engineering for Agents",
  "agent-memory-types": "🟡 Agent Memory Types",
  "single-agent-architecture": "🟡 Single-Agent Architecture",
  "multi-agent-systems": "🟡 Multi-Agent Systems",
  "orchestrator-worker-pattern": "🟡 Orchestrator-Worker Pattern",
  "rag-deep-dive": "🟡 RAG Deep Dive",
  "structured-output": "🟡 Structured Output & JSON Mode",
  "agent-routing": "🟡 Agent Routing & Intent Classification",
  "hierarchical-multi-agent": "🔴 Hierarchical Multi-Agent",
  "agent-communication-protocols": "🔴 Agent Communication Protocols",
  "long-running-agents": "🔴 Long-Running Agents",
  "human-in-the-loop": "🟡 Human-in-the-Loop Workflows",
  "planning-patterns": "🔴 Agent Planning Patterns",
  "context-window-management": "🔴 Context Window Management",
  "agent-evaluation-testing": "🔴 Agent Evaluation & Testing",
  "cost-control-agents": "🔴 Cost Control for Agents",
  "multi-model-routing": "🔴 Multi-Model Routing & Fallback",
  "agent-observability": "🔴 Agent Observability",
  "safety-guardrails": "🔴 Safety & Guardrails",
  "agent-to-agent-protocol": "🔴 Agent-to-Agent Protocol (A2A)",
  "agent-client-protocol": "🔴 Agent Client Protocol (ACP)",
  "model-context-protocol": "⚫ Model Context Protocol",
  "langgraph-stateful-agents": "⚫ LangGraph Stateful Agents",
  "agent-tool-registry": "⚫ Agent Tool Registry"
}
