export default {
  index: { title: '📅 Reservation & Scheduling' },
  'ticketmaster': { title: '🎫 Ticketmaster' },
  'uber-ride-matching': { title: '🚗 Uber (Ride Matching)' },
  'airbnb-listing-search': { title: '🏠 Airbnb (Listing Search)' },
  'uber-backend': { title: '🚗 Uber Backend' },
  'food-delivery': { title: '🍔 Food Delivery' },
  'hotel-booking': { title: '🏨 Hotel Booking' },
  'auction-system': { title: '🔨 Auction System' },
  'task-scheduler': { title: '⏰ Task Scheduler' },
  'meeting-calendar': { title: '📅 Meeting Calendar' },
  'conference-room-booking': { title: '🏢 Conference Room Booking' },
  'automated-trading': { title: '📈 Automated Trading System' },
  'fresh-grocery-delivery': { title: '🛒 15-Min Grocery Delivery' },
  'order-tracking': { title: '📦 Order Tracking System' },
  'airport-baggage': { title: '🧳 Airport Baggage Tracking' },
  'flash-sale': { title: '⚡ Flash Sale System' },
  'public-transportation': { title: '🚌 Public Transportation' },
  'inventory-management': { title: '🏭 Inventory Management' },
  'e-commerce-service': { title: '🛍️ E-Commerce Platform' },
  'online-coupon': { title: '🏷️ Online Coupon System' },
  'air-traffic-control': { title: '✈️ Air Traffic Control' },
  'employee-swap': { title: '🔄 Employee Shift Swap' },
}
