import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { glob } from 'glob';
import matter from 'gray-matter';
import { EDGE_FIELDS, SKIP_NAMES } from './constants.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '../../');
const PAGES_DIR = join(REPO_ROOT, 'docs-site/pages');

export function buildAdjacencyMap(nodes) {
  const adj = new Map();
  for (const [key, node] of nodes) {
    for (const field of EDGE_FIELDS) {
      const targets = node.data[field] || [];
      for (const target of targets) {
        if (!adj.has(target)) adj.set(target, new Set());
        adj.get(target).add(key);
      }
    }
  }
  return adj;
}

export function computeLinkedFrom(key, adj) {
  return Array.from(adj.get(key) || []).sort();
}

export function updateLinkedFrom(rawContent, incoming) {
  const parsed = matter(rawContent);
  const existing = (parsed.data.linked_from || []).slice().sort();
  const sorted = incoming.slice().sort();
  if (JSON.stringify(existing) === JSON.stringify(sorted)) {
    return { changed: false, newContent: rawContent };
  }
  parsed.data.linked_from = sorted;
  const newContent = matter.stringify(parsed.content, parsed.data);
  return { changed: true, newContent };
}

function generateKnowledgeGraph(nodes, adj) {
  const byLayer = { concept: [], solution: [], problem: [], poc: [], 'interview-q': [], 'case-study': [] };
  for (const [key, node] of nodes) {
    const layer = node.data.layer || 'concept';
    if (byLayer[layer]) byLayer[layer].push(key);
  }

  const now = new Date().toISOString();
  const totalNodes = nodes.size;
  const totalEdges = Array.from(adj.values()).reduce((s, v) => s + v.size, 0);

  const lines = [
    '# Knowledge Graph',
    '',
    `> Auto-generated by \`/sync-graph\` on ${now}`,
    `> **${totalNodes} nodes** | **${totalEdges} edges**`,
    '',
    '---',
    '',
    '## Stats',
    '',
    '| Layer | Count |',
    '|-------|-------|',
  ];
  for (const [layer, keys] of Object.entries(byLayer)) {
    lines.push(`| ${layer} | ${keys.length} |`);
  }

  // Diagram 1: concept + solution (theory level)
  lines.push('', '## Diagram 1: Concepts & Solutions', '', '```mermaid', 'graph TD');
  // Cap at 40 nodes — Mermaid struggles to render larger graphs in-browser
  const d1 = [...byLayer.concept, ...byLayer.solution].slice(0, 40);
  for (const key of d1) {
    const id = key.replace(/\//g, '_').replace(/-/g, '_');
    lines.push(`  ${id}["${key.split('/').pop()}"]`);
  }
  for (const key of d1) {
    const node = nodes.get(key);
    if (!node) continue;
    const srcId = key.replace(/\//g, '_').replace(/-/g, '_');
    for (const target of (node.data.see_poc || [])) {
      if (d1.includes(target)) {
        const tgtId = target.replace(/\//g, '_').replace(/-/g, '_');
        lines.push(`  ${srcId} -->|see_poc| ${tgtId}`);
      }
    }
  }
  lines.push('```');

  // Diagram 2: problems
  lines.push('', '## Diagram 2: Problems', '', '```mermaid', 'graph TD');
  // Cap at 40 nodes — Mermaid struggles to render larger graphs in-browser
  const d2 = byLayer.problem.slice(0, 40);
  for (const key of d2) {
    const id = key.replace(/\//g, '_').replace(/-/g, '_');
    lines.push(`  ${id}["${key.split('/').pop()}"]`);
  }
  for (const key of d2) {
    const node = nodes.get(key);
    if (!node) continue;
    const srcId = key.replace(/\//g, '_').replace(/-/g, '_');
    for (const target of (node.data.related_problems || [])) {
      if (d2.includes(target)) {
        const tgtId = target.replace(/\//g, '_').replace(/-/g, '_');
        lines.push(`  ${srcId} -->|related| ${tgtId}`);
      }
    }
  }
  lines.push('```');

  // Diagram 3: poc + interview-q (practice level)
  lines.push('', '## Diagram 3: POCs & Interview Questions', '', '```mermaid', 'graph TD');
  // Cap at 40 nodes — Mermaid struggles to render larger graphs in-browser
  const d3 = [...byLayer.poc, ...byLayer['interview-q']].slice(0, 40);
  for (const key of d3) {
    const id = key.replace(/\//g, '_').replace(/-/g, '_');
    lines.push(`  ${id}["${key.split('/').pop()}"]`);
  }
  lines.push('```');

  // Diagram 4: case-studies
  lines.push('', '## Diagram 4: Case Studies', '', '```mermaid', 'graph TD');
  // Cap at 40 nodes — Mermaid struggles to render larger graphs in-browser
  const d4 = byLayer['case-study'].slice(0, 40);
  for (const key of d4) {
    const id = key.replace(/\//g, '_').replace(/-/g, '_');
    lines.push(`  ${id}["${key.split('/').pop()}"]`);
  }
  lines.push('```');

  // Navigation index tables
  lines.push('', '## Navigation Index', '', '### All Nodes by Layer', '');
  for (const [layer, keys] of Object.entries(byLayer)) {
    if (keys.length === 0) continue;
    lines.push(`#### ${layer}`);
    lines.push('| File | Tags |');
    lines.push('|------|------|');
    for (const key of keys.sort()) {
      const tags = (nodes.get(key)?.data?.tags || []).join(', ');
      lines.push(`| ${key} | ${tags} |`);
    }
    lines.push('');
  }

  // Orphan report
  const orphans = [];
  for (const [key, node] of nodes) {
    const hasOut = EDGE_FIELDS.some(f => (node.data[f] || []).length > 0);
    const hasIn = (node.data.linked_from || []).length > 0;
    if (!hasOut && !hasIn) orphans.push(key);
  }
  lines.push('## Orphan Report', '');
  if (orphans.length === 0) {
    lines.push('No orphaned nodes.');
  } else {
    lines.push(`${orphans.length} orphaned nodes (no links in or out):`);
    for (const o of orphans) lines.push(`- ${o}`);
  }

  writeFileSync(join(PAGES_DIR, 'KNOWLEDGE-GRAPH.md'), lines.join('\n') + '\n');
  console.log(`Generated KNOWLEDGE-GRAPH.md (${totalNodes} nodes, ${totalEdges} edges)`);
}

function printGapReport(nodes) {
  const gaps = {
    conceptNoPoC: [],
    problemNoSolution: [],
    pocNoPrereq: [],
    caseStudyUnreferenced: [],
  };

  const allLinkedFrom = new Set();
  for (const [, node] of nodes) {
    for (const f of (node.data.linked_from || [])) allLinkedFrom.add(f);
  }

  for (const [key, node] of nodes) {
    const layer = node.data.layer;
    if (layer === 'concept' && (node.data.see_poc || []).length === 0) gaps.conceptNoPoC.push(key);
    if (layer === 'problem' && (node.data.solves_with || []).length === 0) gaps.problemNoSolution.push(key);
    if (layer === 'poc' && (node.data.prerequisites || []).length === 0) gaps.pocNoPrereq.push(key);
    if (layer === 'case-study' && !allLinkedFrom.has(key)) gaps.caseStudyUnreferenced.push(key);
  }

  console.log('\n=== GAP REPORT ===');
  console.log(`Concepts with no POC: ${gaps.conceptNoPoC.length}`);
  for (const g of gaps.conceptNoPoC) console.log(`  - ${g}`);
  console.log(`Problems with no solution: ${gaps.problemNoSolution.length}`);
  for (const g of gaps.problemNoSolution) console.log(`  - ${g}`);
  console.log(`POCs with no prerequisites: ${gaps.pocNoPrereq.length}`);
  for (const g of gaps.pocNoPrereq) console.log(`  - ${g}`);
  console.log(`Case studies not referenced: ${gaps.caseStudyUnreferenced.length}`);
  for (const g of gaps.caseStudyUnreferenced) console.log(`  - ${g}`);
}

async function main() {
  const filePaths = await glob(
    ['system-design/**/*.md', 'interview-prep/**/*.md', 'problems-at-scale/**/*.md'],
    { cwd: PAGES_DIR, ignore: ['**/database-archival-poc/**'] }
  );
  const articlePaths = filePaths.filter(f => !SKIP_NAMES.has(f.split('/').pop()));

  const nodes = new Map();
  for (const relPath of articlePaths) {
    const fullPath = join(PAGES_DIR, relPath);
    const content = readFileSync(fullPath, 'utf8');
    const { data } = matter(content);
    const key = relPath.replace(/\.md$/, '');
    nodes.set(key, { fullPath, data, content });
  }

  console.log(`Found ${nodes.size} article nodes`);

  const adj = buildAdjacencyMap(nodes);

  let updatedCount = 0;
  for (const [key, node] of nodes) {
    const incoming = computeLinkedFrom(key, adj);
    const { changed, newContent } = updateLinkedFrom(node.content, incoming);
    if (changed) {
      writeFileSync(node.fullPath, newContent);
      updatedCount++;
      node.data.linked_from = incoming;
    }
  }

  console.log(`Updated linked_from in ${updatedCount} files`);
  generateKnowledgeGraph(nodes, adj);
  printGapReport(nodes);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main().catch(err => { console.error(err); process.exit(1); });
}
