export default {
  index: { title: '🤖 AI & Agents' },
  'rag-qa-agent': { title: '📚 RAG-Based Q&A Agent' },
  'chatbot-framework': { title: '🤖 Chatbot Framework' },
  'code-generation-agent': { title: '💻 Code Generation Agent' },
  'customer-support-agent': { title: '🎧 Customer Support Agent' },
  'deep-research-agent': { title: '🔬 Deep Research Agent' },
  'multi-agent-orchestration': { title: '🎭 Multi-Agent Orchestration' },
  'document-processing-agent': { title: '📄 Document Processing Agent' },
  'content-moderation-agent': { title: '🛡️ Content Moderation Agent' },
  'autonomous-testing-agent': { title: '🧪 Autonomous Testing Agent' },
  'data-analysis-agent': { title: '📊 Data Analysis Agent' },
  'workflow-automation-agent': { title: '⚙️ Workflow Automation Agent' },
  'ai-travel-planning-agent': { title: '✈️ AI Travel Planning Agent' },
  'security-monitoring-agent': { title: '🔐 Security Monitoring Agent' },
  'personal-finance-agent': { title: '💰 Personal Finance Agent' },
  'sales-development-agent': { title: '📧 Sales Development Agent' },
  'medical-triage-agent': { title: '🏥 Medical Triage Agent' },
  'autonomous-trading-agent': { title: '📈 Autonomous Trading Agent' },
}
