export default {
  "design-url-shortener": "URL Shortener",
  "design-notification-system": "Notification System",
  "design-rate-limiter": "Rate Limiter",
  "design-chat-system": "Chat System",
  "design-news-feed": "News Feed",
  "design-video-streaming": "Video Streaming",
  "design-search-autocomplete": "Search Autocomplete",
  "design-ride-sharing": "Ride Sharing",
  "design-payment-system": "Payment System",
  "design-distributed-cache": "Distributed Cache",
  "design-cdn": "CDN",
  "design-api-gateway": "API Gateway",
  "design-job-scheduler": "Job Scheduler",
  "design-file-storage": "File Storage",
  "design-location-service": "Location Service",
  "design-recommendation-engine": "Recommendation Engine",
  "design-ad-click-aggregator": "Ad Click Aggregator",
  "design-web-crawler": "Web Crawler",
  "design-metrics-monitoring": "Metrics & Monitoring",
  "design-distributed-locking": "Distributed Locking",
}
