export default {
  "overview": "Overview",
  "redis-key-value-cache": "Key-Value Cache",
  "redis-counter": "Atomic Counter",
  "redis-distributed-lock": "Distributed Lock",
  "redis-rate-limiting": "Rate Limiting",
  "redis-session-management": "Session Management",
  "redis-job-queue": "Job Queue",
  "redis-pubsub": "Pub/Sub",
  "redis-pubsub-patterns": "Pub/Sub Patterns",
  "redis-streams": "Streams",
  "redis-streams-event-sourcing": "Streams & Event Sourcing",
  "redis-leaderboard": "Leaderboard",
  "redis-hyperloglog": "HyperLogLog",
  "redis-deduplication": "Deduplication",
  "redis-cluster-caching": "Cluster Caching",
  "redis-cluster-sharding": "Cluster Sharding",
  "redis-persistence-strategies": "Persistence Strategies",
  "redis-monitoring-performance": "Monitoring & Performance",
  "redis-atomic-inventory": "Atomic Inventory",
  "redis-banking-transfers": "Banking Transfers",
  "redis-transaction-rollback": "Transaction Rollback",
  "redis-transactions-multi-exec": "Transactions (MULTI/EXEC)",
  "redis-watch-optimistic-locking": "WATCH & Optimistic Locking",
  "redis-lua-scripting-basics": "Lua Scripting Basics",
  "redis-lua-rate-limiting": "Lua Rate Limiting",
  "redis-lua-leaderboards": "Lua Leaderboards",
  "redis-lua-workflows": "Lua Workflows",
  "redis-lua-performance-benchmarks": "Lua Performance Benchmarks"
}
