export default {
  index: { title: '🎯 Object-Oriented Design' },
  'parking-lot': { title: '🅿️ Parking Lot' },
  'vending-machine': { title: '🥤 Vending Machine' },
  'elevator-system': { title: '🛗 Elevator System' },
  'chess-game': { title: '♟️ Chess Game' },
  'atm-system': { title: '🏧 ATM System' },
  'task-management': { title: '✅ Task Management App' },
  'fitness-tracker': { title: '🏃 Fitness Tracking App' },
  'banking-system': { title: '🏦 Banking System' },
  'online-shopping': { title: '🛒 Online Shopping System' },
  'file-system': { title: '📁 File System' },
  'learning-management': { title: '🎓 Learning Management System' },
  'social-media-platform': { title: '📱 Social Media Platform' },
  'iot-smart-home': { title: '🏠 IoT Smart Home' },
  'calendar-system': { title: '📅 Calendar System' },
  'game-state-management': { title: '🎮 Game State Management' },
  'ride-sharing-service': { title: '🚗 Ride-Sharing Service' },
  'entity-component-system': { title: '⚙️ Entity-Component-System (ECS)' },
  'library-management': { title: '📚 Library Management System' },
  'video-streaming-platform': { title: '🎬 Video Streaming Platform' },
  'warehouse-management': { title: '📦 Warehouse Management System' },
  'resource-management': { title: '🔧 Resource Management System' },
  'food-delivery-ood': { title: '🍕 Food Delivery (OOD)' },
}
