export default {
  index: { title: '⚙️ Data Processing' },
  'url-shortener': { title: '🔗 URL Shortener (TinyURL)' },
  'youtube-netflix': { title: '📺 YouTube / Netflix' },
  'facebook-newsfeed': { title: '📰 Facebook Newsfeed' },
  'web-crawler': { title: '🕷️ Web Crawler' },
  'web-cache': { title: '⚡ Web Cache' },
  'live-video-streaming': { title: '🎥 Live Video Streaming' },
  'web-analytics': { title: '📊 Web Analytics' },
  'live-comment-system': { title: '💬 Live Comment System' },
  'top-k-analysis': { title: '🏆 Top-K Analysis' },
  'ad-click-aggregation': { title: '🖱️ Ad Click Aggregation' },
  'log-collection': { title: '📋 Log Collection & Analysis' },
  'real-time-sports-scoring': { title: '🏅 Real-Time Sports Scoring' },
  'real-time-stock-trading': { title: '📈 Real-Time Stock Trading' },
  'podcast-hosting': { title: '🎙️ Podcast Hosting Platform' },
  'nested-comments': { title: '💬 Nested Comments System' },
  'scheduled-digital-transaction': { title: '💳 Scheduled Digital Transactions' },
  'video-view-count': { title: '👁️ Video View Count System' },
  'graph-search-social': { title: '🔍 Graph Search (Social Network)' },
  'event-lifecycle': { title: '🎟️ Event Lifecycle Management' },
  'language-translation': { title: '🌐 Language Translation Service' },
  'weather-reporting': { title: '🌤️ Weather Reporting System' },
  'tagging-service': { title: '🏷️ Tagging Service' },
  'frequently-viewed-products': { title: '🛒 Frequently Viewed Products' },
  'movie-reviews-aggregator': { title: '🎬 Movie Reviews Aggregator' },
  'database-batch-auditing': { title: '🔒 Database Batch Auditing' },
}
