export default {
  "database-crud": "CRUD Operations",
  "database-indexes": "Indexes",
  "database-transactions": "Transactions",
  "database-partitioning": "Partitioning",
  "database-sharding": "Sharding",
  "database-read-replicas": "Read Replicas",
  "database-connection-pooling": "Connection Pooling",
  "database-explain": "EXPLAIN & Query Analysis",
  "database-n-plus-one": "N+1 Query Problem",
  "database-window-functions": "Window Functions",
  "database-materialized-views": "Materialized Views",
  "database-views": "Views",
  "database-triggers": "Triggers",
  "database-check-constraints": "Check Constraints",
  "database-foreign-keys": "Foreign Keys",
  "database-full-text-search": "Full-Text Search",
  "database-jsonb": "JSONB",
  "database-ctes": "CTEs (Common Table Expressions)",
  "database-sequences": "Sequences",
  "database-vacuum": "VACUUM & Autovacuum",
  "database-testing": "Database Testing",
  "database-archival-strategies": "Archival Strategies",
  "postgresql-btree-hash-indexes": "PostgreSQL B-Tree & Hash Indexes",
  "postgresql-composite-covering-indexes": "PostgreSQL Composite & Covering Indexes",
  "postgresql-connection-pooling-replication": "PostgreSQL Connection Pooling & Replication",
  "postgresql-explain-analyze-optimization": "PostgreSQL EXPLAIN ANALYZE Optimization",
  "postgresql-partitioning-strategies": "PostgreSQL Partitioning Strategies",
  "connection-leak-detection": "Connection Leak Detection",
  "connection-pool-sizing": "Connection Pool Sizing"
}
