export default {
  index: { title: '🔧 Infrastructure' },
  'rate-limiter': { title: '🚦 API Rate Limiter' },
  'key-value-store': { title: '🗝️ Key-Value Store' },
  'distributed-messaging': { title: '📬 Distributed Messaging' },
  'distributed-file-system': { title: '📁 Distributed File System' },
  'load-balancer': { title: '⚖️ Load Balancer' },
  'cdn': { title: '🌐 Content Delivery Network' },
  'distributed-counter': { title: '🔢 Distributed Counter' },
  'distributed-locking': { title: '🔐 Distributed Locking' },
  'distributed-tracing': { title: '🔍 Distributed Tracing' },
  'unique-id-generator': { title: '🆔 Unique ID Generator' },
  'metrics-alerting': { title: '📈 Metrics & Alerting' },
  'code-deployment': { title: '🚀 Code Deployment' },
  'container-orchestration': { title: '🐳 Container Orchestration' },
  'hpc-cluster': { title: '🖥️ HPC Cluster' },
  'cloud-backup': { title: '💾 Cloud Backup' },
  'cloud-storage-gateway': { title: '🌩️ Cloud Storage Gateway' },
  'virtualization': { title: '🖧 Virtualization Platform' },
  'disaster-recovery': { title: '🛡️ Disaster Recovery' },
  'hybrid-cloud-orchestrator': { title: '☁️ Hybrid Cloud Orchestrator' },
  'multi-cloud-api-gateway': { title: '🔀 Multi-Cloud API Gateway' },
  'serverless-framework': { title: '⚡ Serverless Framework' },
  'large-scale-graph-processing': { title: '🕸️ Graph Processing at Scale' },
  'big-data-pipeline': { title: '🔄 Big Data Pipeline' },
  'distributed-oltp': { title: '🏦 Distributed OLTP Database' },
  'dns': { title: '🌍 DNS System' },
  'distributed-linked-list': { title: '🔗 Distributed Linked List' },
  'resource-allocation': { title: '🎯 Resource Allocation' },
  'service-pool-allocation': { title: '🏊 Service Pool Allocation' },
  'wide-column-database': { title: '📊 Wide-Column Database' },
  'multi-device-screenshot': { title: '📸 Multi-Device Screenshot Sync' },
  'network-path-analyzer': { title: '🗺️ Network Path Analyzer' },
}
