export default {
  index: "Overview",
  "sliding-window-pattern": "🟡 Sliding Window",
  "two-pointers-pattern": "🟢 Two Pointers",
  "binary-search-on-answer": "🟡 Binary Search on Answer",
  "monotonic-stack-pattern": "🟡 Monotonic Stack",
  "prefix-sum-pattern": "🟢 Prefix Sum",
  "heap-top-k-pattern": "🟡 Heap / Top-K",
  "graph-bfs-dfs-pattern": "🟡 Graph BFS & DFS",
  "dynamic-programming-patterns": "🔴 Dynamic Programming",
  "union-find-pattern": "🟡 Union-Find",
  "interval-scheduling-pattern": "🟡 Interval Scheduling",
  "backtracking-pattern": "🔴 Backtracking",
  "tree-patterns": "🟡 Tree & Binary Tree Patterns",
  "linked-list-patterns": "🟢 Linked List Patterns",
  "greedy-pattern": "🟡 Greedy Algorithms",
  "graph-shortest-path": "🟡 Graph Shortest Path",
  "divide-and-conquer": "🟡 Divide & Conquer",
  "matrix-grid-patterns": "🟡 Matrix & Grid Patterns",
  "string-algorithms": "🔴 String Search Algorithms",
  "bit-manipulation": "🟡 Bit Manipulation",
  "segment-tree-pattern": "🔴 Segment Tree & Fenwick Tree",
  "problem-solving-framework": "🟢 How to Approach Any Problem",
  "algorithms-in-production": "🟡 Algorithms in Production Systems"
}
